vpc_cidr_block            = "10.0.0.0/16"
public_subnet_cidr_block  = ["10.0.0.0/24", "10.0.1.0/24", "10.0.2.0/24"]
private_subnet_cidr_block = ["10.0.3.0/24", "10.0.4.0/24", "10.0.5.0/24"]
env                       = "prod"
region                    = "eu-west-2"
sg_name                   = "vpc-sg-vpc-endpoint"
ecr_repository_name       = "ecs-v2-ecr"
ecs_cluster_name          = "ecs-v2-cluster"
ecs_service_name          = "ecs-v2-service"
ecs_container_memory      = 2048
ecs_container_cpu         = 1024
ecs_task_cpu              = 1024
ecs_task_memory           = 2048
container_name            = "ecs-v2-container"
container_port            = 8000
desired_count             = 1
dynamodb_table_name       = "ecs-v2-dynamodb-table"
cpu_architecture          = "ARM64"
operating_system_family   = "LINUX"
lb_name                   = "ecs-v2-lb"
domain                    = "tm-yahya.com"
max_capacity              = 5
min_capacity              = 1